[package]
name = "k8s-consul-mutator-rs"
description = "A mutating webhook that writes consul key checksums to resoures."
version = "0.1.0"
edition = "2021"
authors = ["Nick Gerakines <nick.gerakines@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ngerakines/something"
license = "MIT"
publish = false
build = "build.rs"

[dependencies]
anyhow = "1"
axum = "0.6.2"
axum-extra = { version = "0.4", default-features = false, features = ["cookie-signed"] }
derive_more = "0.99"
async-trait = {version = "0.1"}
sentry = { version = "0.29", default-features = false, features = ["backtrace", "contexts", "panic", "rustls", "reqwest", "tower", "tracing"] }
sentry-anyhow = "0.29"
sentry-tower = { version = "0.29", features = ["http"] }
sentry-tracing = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.89" }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4" }
tower-http = { version = "0.3", features = ["trace"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parking_lot = "0.12"
crossbeam-utils = "0.8.14"
crossbeam-epoch = "0.9.13"
rand = "0.8"
url = "2.3"
redis = "0.22"
hex = "0.4.3"

[profile.release]
strip = true
lto = true

