apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-consul-mutator-rs
  namespace: k8s-consul-mutator-rs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-consul-mutator-rs
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-consul-mutator-rs
subjects:
- kind: ServiceAccount
  name: k8s-consul-mutator-rs
  namespace: k8s-consul-mutator-rs
roleRef:
  kind: ClusterRole
  name: k8s-consul-mutator-rs
  apiGroup: rbac.authorization.k8s.io
